CREATE TABLE channels(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discord_channel_id BIGINT UNIQUE,
    discord_user_id BIGINT NOT NULL,
    telegram_chat_id BIGINT,
    max_followers INT,
    max_following INT,
    max_tweets INT,
    max_age INT,
    lost_at TIMESTAMP
);